### ISSUE TITLE
npm possibly wrong?

### ISSUE THREAD

**Issue by Tylertron1998** [Hackzzila/krypton#2]
Hi there;

At the bottom of your README.md, it says "npm install krypton" - now, I tried that, and it gave me an empty folder (Basically, anyway) which wasn't by you. Can you confirm if this is the right one?

Thank you!

**Comment by Hackzzila** [comment]
It isn't published to npm yet. Right now you need to run `npm i Hackzzila/krypton`. Even that may have a few bugs as krypton is still in development.

**Comment by Hackzzila** [comment]
Once I email npm to get this package name this will be resolved. Closing for now.
